-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES
FROM BOOK as s JOIN BOOK_SALES as b ON s.BOOK_ID = b.BOOK_ID 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01' 
GROUP BY CATEGORY 
ORDER BY CATEGORY;